name: Terraform Infra + Deploy .NET App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 5. Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      # 6. Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 7. Publish application
      - name: Publish .NET App
        run: dotnet publish FlipkartClone -c Release -o publish

      # 8. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: flipkart-gha-webapp-demo
          package: publish
